<?xml version="1.0"?>
<!-- Soccer Robot -->
<robot name="soccer_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_mass" value=".01"/>
  <xacro:property name="wheel_radius" value=".03"/>
  <xacro:property name="wheel_thickness" value=".01"/>
  <xacro:property name="height" value=".15"/>
  <xacro:property name="mass" value=".5"/>

  <link name='chassis2'>
    <collision name="collision">
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://walle/meshes/soccer_robot.dae"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://walle/meshes/soccer_robot.dae"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
</robot>
