<?xml version="1.0"?>
<!-- Soccer Robot -->
<robot name="soccer_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="SIN45" value="0.7071067812"/>

  <!-- Omni joints -->
  <xacro:macro name="omni" params="namespace parent id mass radius xyz yaw color">
    <link name="omni_link${id}">
      <collision name="collision">
        <geometry>
          <sphere radius="${radius}"/>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <sphere radius="${radius}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="${mass}"/>
        <inertia
          ixx="${2*mass*radius*radius/3}" ixy="0.0" ixz="0.0"
          iyy="${2*mass*radius*radius/3}" iyz="0.0"
          izz="${2*mass*radius*radius/3}"/>
      </inertial>
    </link>
    <gazebo reference="omni_link${id}">
      <material>Gazebo/${color}</material>
    </gazebo>    
    <joint type="continuous" name="omni_joint${id}">
      <origin xyz="${xyz}" rpy="0 ${PI/2} ${yaw}"/>
      <parent link="${parent}"/>
      <child link="omni_link${id}"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <!-- Base -->
  <xacro:macro name="wheel" params="namespace parent id mass radius thickness xyz yaw">
    <link name="wheel${id}">
      <visual name="visual">
        <geometry>
          <cylinder
            radius="${radius}"
            length="${thickness}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass/12 * (3*radius*radius + thickness*thickness)}" ixy="0.0" ixz="0.0"
          iyy="${mass/12 * (3*radius*radius + thickness*thickness)}" iyz="0.0"
          izz="${mass*radius*radius/2}"/>
      </inertial>
    </link>
    <joint type="continuous" name="joint${id}">
      <origin xyz="${xyz}" rpy="0 ${PI/2} ${yaw}"/>
      <parent link="${parent}"/>
      <child link="wheel${id}"/>
      <axis xyz="0 0 1"/>
      <limit effort="0.2" velocity="20.0" />
    </joint>
    <transmission name="tran${id}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint${id}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor${id}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- Omni joints -->
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}a" mass="${mass/10}" radius="${radius/4}" color="White" xyz="${radius}        0                0" yaw="${PI/2}"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}b" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="${SIN45*radius}  ${SIN45*radius}  0" yaw="${3*PI/4}"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}c" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="0                ${radius}        0" yaw="0"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}d" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="${-SIN45*radius} ${SIN45*radius}  0" yaw="${PI/4}"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}e" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="${-radius}       0                0" yaw="${PI/2}"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}f" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="${-SIN45*radius} ${-SIN45*radius} 0" yaw="${3*PI/4}"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}g" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="0                ${-radius}       0" yaw="0"/>
    <xacro:omni namespace="${namespace}" parent="wheel${id}" id="${id}h" mass="${mass/10}" radius="${radius/4}" color="DarkGrey" xyz="${SIN45*radius}  ${-SIN45*radius} 0" yaw="${PI/4}"/>
  </xacro:macro>
</robot>