<?xml version="1.0"?>
<!-- Soccer Robot -->
<robot name="soccer_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:macro name="wheel" params="namespace parent id mass radius thickness xyz yaw">

    <!-- Base -->
    <link name="wheel${id}">
      <collision name="collision">
        <geometry>
          <cylinder
            radius="${radius}"
            length="${thickness}"/>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <box size="${radius*.707} ${radius*.707} ${thickness}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass/12 * (3*radius*radius + thickness*thickness)}" ixy="0.0" ixz="0.0"
          iyy="${mass/12 * (3*radius*radius + thickness*thickness)}" iyz="0.0"
          izz="${mass*radius*radius/2}"/>
      </inertial>
    </link>
    <joint type="continuous" name="joint${id}">
      <origin xyz="${xyz}" rpy="0 ${PI/2} ${yaw}"/>
      <parent link="${parent}"/>
      <child link="wheel${id}"/>
      <axis xyz="0 0 1"/>
    </joint>
    <transmission name="tran${id}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="joint${id}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor${id}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- Omni joints -->
    <link name="wheel${id}_omni1">
      <collision name="collision">
        <geometry>
          <sphere radius="${radius/6}"/>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <box size="${radius/6} ${radius/6} ${thickness/6}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass/12 * (3*radius*radius + thickness*thickness)}" ixy="0.0" ixz="0.0"
          iyy="${mass/12 * (3*radius*radius + thickness*thickness)}" iyz="0.0"
          izz="${mass*radius*radius/2}"/>
      </inertial>
    </link>
    <joint type="fixed" name="joint${id}_omni1">
      <origin xyz="${radius} 0 0" rpy="0 ${PI/2} ${PI/2}"/>
      <parent link="wheel${id}"/>
      <child link="wheel${id}_omni1"/>
      <axis xyz="0 0 1"/>
    </joint>

  </xacro:macro>
</robot>
